import os

RABBITMQ_HOST = os.getenv('RABBITMQ_HOST', None)
RABBITMQ_PORT = os.getenv('RABBITMQ_PORT', None)
RABBITMQ_USER = os.getenv('RABBITMQ_USER', None)
RABBITMQ_PASSWORD = os.getenv('RABBITMQ_PASSWORD', None)
